version: "3"
services:
  front:
    image: tarefas_front
    ports:
      - "3000:80"
  back:
    image: tarefas_back
    environment:
      - DATABASE_URL=mongodb://bd/tarefas
      - SERVER_PORT=5000
    ports:
      - "5000:5000"
  bd:
    image: mongo
    volumes:
      - "/home/rodrigo/dev/db:/data/db"
